sudo: required
language: java
jdk: oraclejdk8
addons:
 sonarcloud:
   organization: krishnaMurthy-github
   token:
     secure:b90efdaf41dbb64cc3067f5cdd54ac41dbbe201c
before_install:
- chmod +x mvnw

script:
- "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
cache:
 directories:
 - "$HOME/.m2/repository"
 - "$HOME/.sonar/cache"