sudo: required
language: java
jdk: oraclejdk8
addons:
 sonarcloud:
   organization:  krishnamurthy14-github
   token:
    16ab6a2c6d025ae5aa8b78ffe9ce3a9a6bc02fec

before_install:
- chmod +x mvnw

script:
- "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
cache:
 directories:
 - "$HOME/.m2/repository"
 - "$HOME/.sonar/cache"